#server:
#    port: 8088
#spring:
#    data:
#        mongodb:
#            host: cluster0.k546m3d.mongodb.net
#            port: 27017
#            database: acwa
#            username: acwa
#            password: 3w8wrjxdAJXJpVC6
#            authenticationDatabase: admin
